In [22]:
import numpy as np
import pandas as pd

In [23]:
data = pd.read_csv("./Iris.csv")
data.drop(["Id"], axis=1, inplace=True)
data.head(5)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [24]:
def ReLU(x):
    return int(x > 0)

def sigmoid(x):
    return 1/(1 + np.exp(-x))

def deriv_sigmoid(x):
    return sigmoid(x)*(1 - sigmoid(x))

In [33]:
2**((43-1)/8)

38.05462768008707

In [26]:
class NN:
    def __init__(self, input_n, output_n, hidden_layers, hidden_neurons, input_values):
        # Layers & Neurons
        self.input_layer = np.array(input_values)
        self.output_layer = np.zeros((output_n, 1))
        self.hidden_layers = []
        self.hidden_neurons = hidden_neurons
        for i in range(hidden_layers):
            self.hidden_layers.append(np.random.uniform(0,1,(hidden_neurons, 1)))
        #print(f"Input Layer: {self.input_layer.shape}\nOutput Layer: {self.output_layer.shape}\nHidden layers: {len(self.hidden_layers)}x{self.hidden_layers[0].shape}\nHidden Neurons: {self.hidden_neurons}\n")
        self.initialize_weights(input_n, output_n, hidden_layers, hidden_neurons)
        
    def display_neurons(self):
        print("Input Layer:\n", self.input_layer,"\n")
        print("Output Layer:\n", self.output_layer.T,"\n")

    def display_weights(self):
        print("Input Weights:\n",self.input_weights,"\n")
        print("Output Weights:\n",self.output_weights, "\n")
        print("Hidden Layer Weights:\n",self.hidden_layers_weights,"\n")

    def initialize_weights(self, input_n, output_n, hidden_layers, hidden_neurons):
        self.input_weights = np.random.uniform(0,1,(input_n, hidden_neurons))
        self.output_weights = np.random.uniform(0,1,(hidden_neurons, output_n))
        self.hidden_layers_weights = []
        for i in range(hidden_layers - 1):
            self.hidden_layers_weights.append(np.random.uniform(0,1,(hidden_neurons, hidden_neurons)))
        #print(f"Input Weights: {self.input_weights.shape}\nOutput Weights: {self.output_weights.shape}\nHidden Layer Weights:")

    def forward_pass(self, input_data):
        input_activation = np.dot(input_data, self.input_weights)
        for i in range(len(self.hidden_layers)-1):
            self.hidden_layers[i] = np.dot(input_activation, self.hidden_layers_weights[i])
        self.output_layer = np.dot(self.hidden_layers[-1].T, self.output_weights)
    
    def backprop(self, target_output):
        pass

    def update_params(self, learning_rate):
        pass

In [27]:
neural_net = NN(input_n=4, output_n=3, hidden_layers=1, hidden_neurons=3, input_values=[5.1, 3.5, 1.4, 0.2])

In [28]:
neural_net.display_neurons()
neural_net.display_weights()

Input Layer:
 [5.1 3.5 1.4 0.2] 

Output Layer:
 [[0. 0. 0.]] 

Input Weights:
 [[0.93230269 0.60258114 0.75063642]
 [0.99290045 0.23906449 0.28724559]
 [0.95430837 0.69739797 0.23334993]
 [0.24349437 0.19791969 0.54969922]] 

Output Weights:
 [[0.01765091 0.55294386 0.31780903]
 [0.9354251  0.97949691 0.92948807]
 [0.41192765 0.36947999 0.01522872]] 

Hidden Layer Weights:
 [] 



In [31]:
neural_net.forward_pass([5.1, 3.5, 1.4, 0.2])
neural_net.display_neurons()
neural_net.display_weights()

Input Layer:
 [5.1 3.5 1.4 0.2] 

Output Layer:
 [[0.8292972 ]
 [1.20517687]
 [0.72195133]] 

Input Weights:
 [[0.93230269 0.60258114 0.75063642]
 [0.99290045 0.23906449 0.28724559]
 [0.95430837 0.69739797 0.23334993]
 [0.24349437 0.19791969 0.54969922]] 

Output Weights:
 [[0.01765091 0.55294386 0.31780903]
 [0.9354251  0.97949691 0.92948807]
 [0.41192765 0.36947999 0.01522872]] 

Hidden Layer Weights:
 [] 



In [30]:
neural_net.backprop(np.array([1,0,0]))
neural_net.update_params(0.01)